### ISSUE TITLE
This whole repo is bad

### ISSUE THREAD

**Issue by rsadwick** [mattjennings/svelte-phaser#21]
The use of svelte and phaser should be designed so the UI is handled in svelete and the rest is handled in canvas.  Why on earth are you combining both?  I'm sure you have your uses but this is not the right direction at all.

**Comment by mattjennings** [comment]
This library was intended to be a way to write Phaser applications declaratively. See [Svelte Cubed](https://svelte-cubed.vercel.app), [React Three Fiber](https://github.com/pmndrs/react-three-fiber), etc. If you wanted to use Svelte for just the UI you can certainly do that without any special library.

Feel free to disagree with the approach but please don't make an issue just to say "this is bad".
